### ISSUE TITLE
Chat button within Trilium no longer working

### ISSUE THREAD

**Issue by perfectra1n** [soulsands/trilium-chat#12]
Hi there!

I'm not sure if I'm doing something wrong, but it looks like the "Chat" button just isn't cooperating with the latest version of Trilium:
![trilium_KkUpVVD5KR](https://github.com/soulsands/trilium-chat/assets/2390633/162abca6-cd6a-4e6b-b2d1-12b35a031162)

Even though the cursor does highlight and show the word "Chat" after resizing the window, when clicking, it does not perform any action.

![image](https://github.com/soulsands/trilium-chat/assets/2390633/33be2e59-9b64-4087-9d4a-1122d11461c8)

However, it does work when using the hotkey.

**Comment by soulsands** [comment]
Thank you so much for your feedback. This is an interesting bug, the button behaves a lot like point-events:none, but even further, it couldn't even be selected in debug. There was a very suspicious property,[ app-region:drag](https://www.electronjs.org/docs/latest/tutorial/window-customization#set-custom-draggable-region), and after some investigation, it turns out that was causing it. The solution was to move the button to a different location.  😀

**Comment by perfectra1n** [comment]
My frontend JS skills are nearly non-existent, so I appreciate you reviewing the issue and fixing it! :)
